#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

pass() {
  echo "PASS: $*"
}

TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/coresearch-validate.XXXXXX")"
case "$TMP_ROOT" in
  /tmp/*|/private/tmp/*|/var/folders/*|/private/var/folders/*) ;;
  *) fail "unexpected temporary root: $TMP_ROOT" ;;
esac

cleanup() {
  python3 - "$TMP_ROOT" <<'PY'
from pathlib import Path
import shutil
import sys

path = Path(sys.argv[1]).resolve()
allowed = (Path("/tmp").resolve(), Path("/private/tmp").resolve(), Path("/private/var/folders").resolve())
if any(root == path or root in path.parents for root in allowed):
    shutil.rmtree(path, ignore_errors=True)
PY
}
trap cleanup EXIT

TOML_PYTHON=""
for candidate in python3 python3.13 python3.12 python3.11; do
  if command -v "$candidate" >/dev/null 2>&1 && "$candidate" -c 'import tomllib' >/dev/null 2>&1; then
    TOML_PYTHON="$(command -v "$candidate")"
    break
  fi
done
[[ -n "$TOML_PYTHON" ]] || fail "Python 3.11+ with standard-library tomllib is required for native Codex role validation"

python3 -m json.tool .codex-plugin/plugin.json >/dev/null
python3 -m json.tool skills/manifest.json >/dev/null
python3 -m json.tool agents/manifest.json >/dev/null
python3 - <<'PY'
from pathlib import Path

for rel in ("scripts/harness.py", "skills/research-survey/crawler.py"):
    compile(Path(rel).read_text(), rel, "exec")
PY
bash -n scripts/install.sh
bash -n scripts/link-local.sh
bash -n scripts/validate.sh
bash -n harness
bash -n bin/harness
pass "static manifests, Python, and shell entry points parse without generated bytecode"

"$TOML_PYTHON" - <<'PY'
from pathlib import Path
import json
import re
import tomllib

manifest = json.loads(Path("agents/manifest.json").read_text())
roles = {item["name"]: item for item in manifest["roles"]}
assert manifest["role_description_version"] == 2
files = sorted(Path("agents/codex").glob("*.toml"))
assert len(files) == 8, files
for path in files:
    with path.open("rb") as handle:
        config = tomllib.load(handle)
    name = config["name"]
    assert path.name == f"{name}.toml", path
    assert name in roles, name
    pin = roles[name]["providers"]["codex"]
    assert config["model"] == pin["model"], (path, config["model"], pin["model"])
    assert config["model_reasoning_effort"] == pin["effort"], (path, config["model_reasoning_effort"], pin["effort"])
    expected_sandbox = "workspace-write" if roles[name]["capability"] == "workspace-write" else "read-only"
    assert config["sandbox_mode"] == expected_sandbox, (path, config["sandbox_mode"], expected_sandbox)
    normalized = " ".join(config["developer_instructions"].split())
    for skill in roles[name]["skills"]:
        assert skill in normalized, (path, skill)
    assert "Load the assigned primary skill" in normalized, path
    assert "working_modes" in normalized, path
    assert re.search(r"spawn(?:ing)? subagents", normalized), path
PY
pass "all eight Codex role definitions parse with tomllib and match the manifest"

python3 - <<'PY'
from pathlib import Path
import json
import re


def frontmatter(path):
    text = path.read_text()
    assert text.startswith("---\n"), path
    raw, body = text[4:].split("\n---\n", 1)
    data = {}
    current = None
    for line in raw.splitlines():
        if line.startswith("  - "):
            assert current, (path, line)
            data.setdefault(current, []).append(line[4:])
        elif ": " in line:
            current, value = line.split(": ", 1)
            data[current] = value
        elif line.endswith(":"):
            current = line[:-1]
            data[current] = []
        else:
            raise AssertionError((path, line))
    return data, body


expected_skills = {
    "coresearch", "research-design", "research-survey", "research-loop",
    "research-gap", "research-dialectic", "research-causal",
    "research-engineer", "research-qualitative", "research-write",
    "research-review", "research-rebuttal", "research-verify",
    "research-audit", "research-adversary",
}
skill_manifest = json.loads(Path("skills/manifest.json").read_text())
owned = [item["name"] for item in skill_manifest["owned"]]
assert len(owned) == 15 and set(owned) == expected_skills
assert "external_routes" not in skill_manifest
assert "aliases" not in skill_manifest and "companions" not in skill_manifest

required_sections = ["## What & When", "## Procedure", "## Output", "## Reject when", "## State & Handoff"]
for name in owned:
    skill_dir = Path("skills") / name
    path = skill_dir / "SKILL.md"
    assert path.is_file(), path
    assert (skill_dir / "_coresearch").exists(), skill_dir
    text = path.read_text()
    match = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    assert match, path
    assert re.search(rf"(?m)^name:\s*{re.escape(name)}\s*$", match.group(1)), path
    if name != "coresearch":
        positions = [text.find(heading) for heading in required_sections]
        assert all(position >= 0 for position in positions) and positions == sorted(positions), (path, positions)
        assert "Re-entry: return to `coresearch`" in text, path

manifest = json.loads(Path("agents/manifest.json").read_text())
assert manifest["schema_version"] == 1
assert manifest["role_description_version"] == 2
expected_roles = {
    "coresearch-planner": {"codex": ("gpt-5.6-sol", "xhigh"), "claude": ("claude-opus-5", "xhigh")},
    "coresearch-researcher": {"codex": ("gpt-5.6-terra", "high"), "claude": ("claude-sonnet-5", "high")},
    "coresearch-reader": {"codex": ("gpt-5.6-luna", "low"), "claude": ("claude-haiku-4-5-20251001", "low")},
    "coresearch-implementer": {"codex": ("gpt-5.6-luna", "medium"), "claude": ("claude-haiku-4-5-20251001", "medium")},
    "coresearch-experimenter": {"codex": ("gpt-5.6-luna", "medium"), "claude": ("claude-haiku-4-5-20251001", "medium")},
    "coresearch-debugger": {"codex": ("gpt-5.6-sol", "high"), "claude": ("claude-opus-5", "high")},
    "coresearch-synthesizer": {"codex": ("gpt-5.6-sol", "low"), "claude": ("claude-opus-5", "low")},
    "coresearch-verifier": {"codex": ("gpt-5.6-sol", "xhigh"), "claude": ("claude-opus-5", "xhigh")},
}
roles = {item["name"]: item for item in manifest["roles"]}
assert set(roles) == set(expected_roles) and len(roles) == 8
for name, expected in expected_roles.items():
    role = roles[name]
    assert role["capability"] in {"read-only", "workspace-write"}
    assert role["skills"] and all(skill in expected_skills for skill in role["skills"])
    for provider, (model, effort) in expected.items():
        assert (role["providers"][provider]["model"], role["providers"][provider]["effort"]) == (model, effort)

claude_files = sorted(Path("agents/claude").glob("*.md"))
assert len(claude_files) == 8
for path in claude_files:
    config, body = frontmatter(path)
    name = config["name"]
    assert path.name == f"{name}.md" and name in roles
    pin = roles[name]["providers"]["claude"]
    assert (config["model"], config["effort"]) == (pin["model"], pin["effort"])
    assert config["skills"] == roles[name]["skills"]
    tools = set(config["tools"])
    if roles[name]["capability"] == "read-only":
        assert not tools & {"Edit", "Write"}
        assert config["permissionMode"] == "plan"
    else:
        assert {"Edit", "Write", "Bash"}.issubset(tools)
        assert config["permissionMode"] == "acceptEdits"
    normalized_body = " ".join(body.split())
    assert "coresearch-managed: role-description-version=2" in body
    assert "Load the assigned primary skill" in normalized_body, path
    assert "working_modes" in normalized_body, path
    assert re.search(r"spawn(?:ing)? subagents", normalized_body)

for role in roles.values():
    for provider in ("codex", "claude"):
        model = role["providers"][provider]["model"]
        assert model not in {"gpt-5.6", "opus", "sonnet", "haiku", "inherit"}, (role["name"], provider, model)
        assert role["providers"][provider]["effort"] in {"low", "medium", "high", "xhigh"}

contract = " ".join(Path("skills/coresearch/references/research-contract.md").read_text().lower().split())
for phrase in (
    "no major claim without supporting evidence",
    "no novelty without closest-work comparison",
    "no causal language without identification",
):
    assert phrase in contract, phrase
router = Path("skills/coresearch/SKILL.md").read_text()
assert "first-stop router" in router
assert "one primary research stage and one primary skill" in router
engineer = Path("skills/research-engineer/SKILL.md").read_text().lower()
assert "implementation" in engineer and "experiment" in engineer and "research insight" in engineer

ponytail_path = Path("skills/coresearch/references/ponytail.md")
caveman_path = Path("skills/coresearch/references/caveman.md")
assert ponytail_path.is_file() and caveman_path.is_file()
ponytail = " ".join(ponytail_path.read_text().lower().split())
caveman = " ".join(caveman_path.read_text().lower().split())
for phrase in (
    "minimal durable research engineering",
    "not a research stage",
    "claim-bearing evaluation",
    "must not change model or role selection",
):
    assert phrase in ponytail, phrase
for phrase in (
    "communication compression",
    "not a research stage",
    "must not compress away",
    "must not change model or role selection",
):
    assert phrase in caveman, phrase
assert "[ponytail.md](references/ponytail.md)" in router
assert "[caveman.md](references/caveman.md)" in router

agent_routing = Path("skills/coresearch/references/agent-routing.md").read_text()
assert "working_modes" in agent_routing
assert "ponytail" in agent_routing.lower() and "caveman" in agent_routing.lower()
for phrase in ("assignment_id", "depends_on", "join", "multiple independent assignments"):
    assert phrase in agent_routing.lower(), phrase

loop = Path("skills/research-loop/SKILL.md").read_text()
adapter = Path("skills/coresearch/references/execution-adapters.md").read_text()
ledger = Path("skills/coresearch/references/state-ledger.md").read_text()
assert "working_modes" in adapter
for artifact in (
    "docs/research/runs/<run-id>/mission.md",
    "docs/research/runs/<run-id>/sandbox.md",
    "docs/research/runs/<run-id>/result.json",
):
    assert artifact in loop and artifact in adapter, artifact
match = re.search(r"New runs use result schema version 2:\n\n```json\n(.*?)\n```", loop, re.S)
assert match, "research-loop result schema example missing"
result_example = json.loads(match.group(1))
assert result_example["schema_version"] == 2
assert "role" not in result_example and "requested_model" not in result_example
assert isinstance(result_example["role_runs"], list) and len(result_example["role_runs"]) == 1
role_run = result_example["role_runs"][0]
for field in (
    "assignment_id", "role", "status", "requested_model", "requested_effort",
    "observed_model", "observed_effort", "routing_status", "artifacts",
    "validators", "stop_reason",
):
    assert field in role_run, field
for field in (
    "schema_version", "run_id", "mission_path", "status", "host", "goal_id",
    "role_runs", "artifacts", "validators", "claim_evidence", "ledger_updates",
    "remaining_risks", "stop_reason",
):
    assert field in loop and field in adapter, field
assert "schema version 1" in loop.lower() and "remains valid" in loop.lower()
assert "assignment_id" in adapter and "depends_on" in adapter
for phrase in ("hypotheses", "evaluation contract", "validators", "sandbox", "retry/fix budget", "stop conditions"):
    assert phrase.lower() in loop.lower(), phrase
assert "docs/research/decisions/ledger.yaml" in ledger
assert "A ledger without `execution_state` remains valid" in ledger
assert "active_run: { id, mission_path, host, status }" in ledger
assert "completed_runs: [{ id, result_path, status }]" in ledger
assert "/goal Execute docs/research/runs/<run-id>/mission.md" in adapter
assert "same `mission.md` and `sandbox.md`" in adapter

link_re = re.compile(r"\[[^\]]*\]\(([^)]+)\)")
checked = 0
for path in sorted(Path("skills").rglob("*.md")):
    for raw in link_re.findall(path.read_text()):
        if raw.startswith(("http://", "https://", "mailto:", "#")):
            continue
        target = raw.split("#", 1)[0]
        if target:
            checked += 1
            assert (path.parent / target).resolve().exists(), (path, target)

design = Path("DESIGN.md").read_text()
required_design = (
    "## 1. Purpose and non-goals", "## 2. Design invariants",
    "## 3. Repository structure and ownership", "## 4. Research control flow",
    "## 5. Skill architecture", "## 6. Role architecture",
    "## 7. Host adapters", "## 8. State and artifact model",
    "## 9. Installation topology", "## 10. Trust and safety boundaries",
    "## 11. Extension guide", "## 12. Validation and lifecycle",
    "## 13. Architectural decisions", "## Single sources of truth",
)
for heading in required_design:
    assert heading in design, heading
assert design.count("```mermaid") == 3
for raw in link_re.findall(design):
    if raw.startswith(("http://", "https://", "#")):
        continue
    target = raw.split("#", 1)[0]
    assert (Path(target)).resolve().exists(), target

for rel in ("README.md", "AGENTS.md"):
    assert "[`DESIGN.md`](DESIGN.md)" in Path(rel).read_text(), rel

table_re = re.compile(r"^\| `(coresearch-[a-z-]+)` \| `([^`]+)` / `([^`]+)` \| `([^`]+)` / `([^`]+)` \|", re.M)
expected_table = {
    name: (pins["codex"][0], pins["codex"][1], pins["claude"][0], pins["claude"][1])
    for name, pins in expected_roles.items()
}
for rel in ("README.md", "templates/research/AGENTS.md"):
    rows = {name: (cm, ce, hm, he) for name, cm, ce, hm, he in table_re.findall(Path(rel).read_text())}
    assert rows == expected_table, (rel, rows)

plugin = json.loads(Path(".codex-plugin/plugin.json").read_text())
assert plugin["skills"] == "./skills/"
for forbidden in ("agents", "prompts", "hooks"):
    assert forbidden not in plugin

legacy = "o" + "mx"
active = [
    Path("AGENTS.md"), Path("README.md"), Path("DESIGN.md"),
    Path("templates/research/AGENTS.md"), Path(".codex-plugin/plugin.json"),
    Path(".gitignore"), Path("skills/manifest.json"), Path("agents/manifest.json"),
    Path("scripts/harness.py"), Path("scripts/install.sh"),
    Path("scripts/link-local.sh"), Path("scripts/validate.sh"),
]
active.extend(sorted(Path("skills").rglob("*.md")))
active.extend(sorted(Path("agents").rglob("*.toml")))
active.extend(sorted(Path("agents").rglob("*.md")))
for path in active:
    text = path.read_text(errors="replace")
    if path == Path("DESIGN.md"):
        text = text.replace("docs/migrations/from-" + legacy + ".md", "")
    assert legacy not in text.lower(), path
    assert "." + legacy not in text.lower(), path
    assert "<!-- " + legacy.upper() + ":" not in text, path

ignore = Path(".gitignore").read_text()
assert ".tmp/" in ignore and "." + legacy + "/" not in ignore.lower()
assert "CLAUDE_CODE_SUBAGENT_MODEL" in Path("scripts/harness.py").read_text()
assert "probe-models" in Path("scripts/harness.py").read_text()
assert Path("docs/migrations/from-" + legacy + ".md").is_file()
print(f"checked {checked} relative skill links")
PY
pass "15-skill research contracts, 8-role parity, DESIGN, documentation drift, and zero active coupling"

SKILLS=()
while IFS= read -r name; do SKILLS+=("$name"); done < <(python3 - <<'PY'
import json
for item in json.load(open("skills/manifest.json"))["owned"]:
    print(item["name"])
PY
)
ROLES=()
while IFS= read -r name; do ROLES+=("$name"); done < <(python3 - <<'PY'
import json
for item in json.load(open("agents/manifest.json"))["roles"]:
    print(item["name"])
PY
)

surface_has() {
  local surface="$1"
  local provider="$2"
  [[ "$surface" == "both" || "$surface" == "$provider" ]]
}

verify_provider_install() {
  local provider="$1"
  local root="$2"
  local mode="$3"
  local suffix
  suffix=".toml"
  [[ "$provider" == "claude" ]] && suffix=".md"
  local name
  for name in "${SKILLS[@]}"; do
    [[ -f "$root/skills/$name/SKILL.md" ]] || fail "$provider install missing skill $name at $root"
    if [[ "$mode" == "symlink" ]]; then
      [[ -L "$root/skills/$name" ]] || fail "$provider $name is not a skill symlink"
    else
      [[ ! -L "$root/skills/$name" ]] || fail "$provider $name unexpectedly symlinked in copy mode"
    fi
  done
  for name in "${ROLES[@]}"; do
    [[ -f "$root/agents/$name$suffix" ]] || fail "$provider install missing role $name at $root"
    if [[ "$mode" == "symlink" ]]; then
      [[ -L "$root/agents/$name$suffix" ]] || fail "$provider $name is not a role symlink"
    else
      [[ ! -L "$root/agents/$name$suffix" ]] || fail "$provider $name unexpectedly symlinked in copy mode"
    fi
  done
}

for scope in user project; do
  for mode in copy symlink; do
    for surface in codex claude both; do
      fixture="$TMP_ROOT/install-$scope-$mode-$surface"
      mkdir -p "$fixture/project"
      log="$TMP_ROOT/install-$scope-$mode-$surface.log"
      if [[ "$scope" == "user" ]]; then
        command=(./harness install --scope user --surface "$surface" --mode "$mode" --codex-home "$fixture/codex" --claude-home "$fixture/claude")
      else
        command=(./harness install --scope project --surface "$surface" --mode "$mode" --project-dir "$fixture/project")
      fi
      "${command[@]}" >"$log" 2>&1 || fail "install matrix failed: $scope/$mode/$surface (log $log)"
      "${command[@]}" >>"$log" 2>&1 || fail "install idempotency failed: $scope/$mode/$surface (log $log)"
      if surface_has "$surface" codex; then
        root="$fixture/codex"
        [[ "$scope" == "project" ]] && root="$fixture/project/.codex"
        verify_provider_install codex "$root" "$mode"
      fi
      if surface_has "$surface" claude; then
        root="$fixture/claude"
        [[ "$scope" == "project" ]] && root="$fixture/project/.claude"
        verify_provider_install claude "$root" "$mode"
      fi
    done
  done
done
pass "user/project x copy/symlink x codex/claude/both install matrix and idempotency"

collision="$TMP_ROOT/collision"
mkdir -p "$collision/skills/coresearch" "$collision/agents"
printf '%s\n' 'external skill content' > "$collision/skills/coresearch/SKILL.md"
printf '%s\n' 'name = "coresearch-planner"' 'model = "external-model"' > "$collision/agents/coresearch-planner.toml"
skill_before="$(shasum -a 256 "$collision/skills/coresearch/SKILL.md" | cut -d ' ' -f 1)"
role_before="$(shasum -a 256 "$collision/agents/coresearch-planner.toml" | cut -d ' ' -f 1)"
if ./harness install --scope user --surface codex --mode copy --codex-home "$collision" >"$TMP_ROOT/collision.log" 2>&1; then
  fail "install overwrote or accepted unrelated same-name entries"
fi
[[ "$skill_before" == "$(shasum -a 256 "$collision/skills/coresearch/SKILL.md" | cut -d ' ' -f 1)" ]] || fail "unrelated skill changed"
[[ "$role_before" == "$(shasum -a 256 "$collision/agents/coresearch-planner.toml" | cut -d ' ' -f 1)" ]] || fail "unrelated role changed"
grep -q 'Refusing to replace unrelated skill' "$TMP_ROOT/collision.log" || fail "skill collision message missing"
grep -q 'Refusing to replace unrelated role' "$TMP_ROOT/collision.log" || fail "role collision message missing"

forced="$TMP_ROOT/forced"
mkdir -p "$forced/agents"
printf '%s\n' 'external role' > "$forced/agents/coresearch-planner.toml"
./harness install --scope user --surface codex --mode copy --codex-home "$forced" --force >"$TMP_ROOT/forced.log" 2>&1
grep -q 'coresearch-managed: role-description-version=2' "$forced/agents/coresearch-planner.toml" || fail "explicit --force did not replace role"

stale="$TMP_ROOT/stale"
mkdir -p "$stale/skills/paper-design" "$stale/agents"
printf '%s\n' 'coresearch' > "$stale/skills/paper-design/_coresearch"
printf '%s\n' '---' 'name: paper-design' 'description: compatibility shim retained for migration' '---' > "$stale/skills/paper-design/SKILL.md"
printf '%s\n' '# coresearch-managed: role-description-version=1' 'name = "coresearch-old"' > "$stale/agents/coresearch-old.toml"
printf '%s\n' 'unrelated' > "$stale/agents/coresearch-external.toml"
./harness install --scope user --surface codex --mode copy --codex-home "$stale" >"$TMP_ROOT/stale.log" 2>&1
[[ ! -e "$stale/skills/paper-design" ]] || fail "recognized stale skill was not pruned"
[[ ! -e "$stale/agents/coresearch-old.toml" ]] || fail "recognized stale role was not pruned"
[[ -f "$stale/agents/coresearch-external.toml" ]] || fail "unrelated stale-name role was removed"
pass "external entries are preserved; explicit force and recognized stale-entry pruning are bounded"

repair_codex="$TMP_ROOT/repair-codex"
repair_claude="$TMP_ROOT/repair-claude"
./harness link --surface both --codex-home "$repair_codex" --claude-home "$repair_claude" >"$TMP_ROOT/repair-setup.log" 2>&1
unlink "$repair_codex/skills/research-loop"
ln -s "$ROOT_DIR/skills/research-loop-missing" "$repair_codex/skills/research-loop"
unlink "$repair_claude/agents/coresearch-reader.md"
ln -s "$ROOT_DIR/agents/claude/coresearch-reader-missing.md" "$repair_claude/agents/coresearch-reader.md"
./harness repair --surface both --codex-home "$repair_codex" --claude-home "$repair_claude" --no-self-install --no-validate >"$TMP_ROOT/repair.log" 2>&1 || fail "repair failed (log $TMP_ROOT/repair.log)"
[[ -e "$repair_codex/skills/research-loop" ]] || fail "repair left broken managed skill"
[[ -e "$repair_claude/agents/coresearch-reader.md" ]] || fail "repair left broken managed role"
grep -q 'Doctor result: PASS' "$TMP_ROOT/repair.log" || fail "repair did not finish with strict doctor"

repair_project="$TMP_ROOT/repair-project"
mkdir -p "$repair_project"
./harness install --scope project --surface both --mode copy --project-dir "$repair_project" >"$TMP_ROOT/repair-project-setup.log" 2>&1
unlink "$repair_project/.codex/skills/research-loop/SKILL.md"
unlink "$repair_project/.claude/agents/coresearch-reader.md"
./harness repair "$repair_project" --scope project --mode copy --surface both --no-self-install --no-validate >"$TMP_ROOT/repair-project.log" 2>&1 || fail "project copy repair failed (log $TMP_ROOT/repair-project.log)"
[[ -f "$repair_project/.codex/skills/research-loop/SKILL.md" ]] || fail "project repair left copied skill broken"
[[ -f "$repair_project/.claude/agents/coresearch-reader.md" ]] || fail "project repair left copied role broken"
[[ ! -L "$repair_project/.codex/skills/coresearch" ]] || fail "project copy repair silently changed mode to symlink"
grep -q 'Mode: copy' "$TMP_ROOT/repair-project.log" || fail "project repair ignored requested copy mode"
grep -q 'Scope: project' "$TMP_ROOT/repair-project.log" || fail "project repair ignored requested scope"
grep -q 'Doctor result: PASS' "$TMP_ROOT/repair-project.log" || fail "project repair did not validate the project install"

repair_collision="$TMP_ROOT/repair-collision"
mkdir -p "$repair_collision/agents"
printf '%s\n' 'external repair role' > "$repair_collision/agents/coresearch-planner.toml"
if ./harness repair --surface codex --mode copy --codex-home "$repair_collision" --no-self-install --no-validate >"$TMP_ROOT/repair-collision.log" 2>&1; then
  fail "repair silently replaced or accepted an unrelated role collision"
fi
grep -q '^external repair role$' "$repair_collision/agents/coresearch-planner.toml" || fail "repair overwrote an unrelated role"

update_project="$TMP_ROOT/update-project"
mkdir -p "$update_project"
(cd "$update_project" && "$ROOT_DIR/harness" update --scope project --mode copy --surface codex --no-validate) >"$TMP_ROOT/update-project.log" 2>&1
[[ -f "$update_project/.codex/skills/coresearch/SKILL.md" ]] || fail "project update omitted copied skills"
[[ -f "$update_project/.codex/agents/coresearch-verifier.toml" ]] || fail "project update omitted copied roles"
[[ ! -L "$update_project/.codex/skills/coresearch" ]] || fail "project update silently changed mode to symlink"
pass "repair and update honor scope/mode and preserve unrelated collisions"

wrapper="$TMP_ROOT/wrapper"
./scripts/install.sh --scope user --surface codex --mode copy --codex-home "$wrapper" >"$TMP_ROOT/wrapper.log" 2>&1
[[ -f "$wrapper/skills/coresearch/SKILL.md" && -f "$wrapper/agents/coresearch-verifier.toml" ]] || fail "thin install wrapper omitted skills or roles"
pass "shell install wrapper delegates to canonical harness behavior"

project="$TMP_ROOT/prompt-project"
mkdir -p "$project"
printf '%s\n' 'PROJECT HEADER' > "$project/AGENTS.md"
./harness init "$project" --bridge >"$TMP_ROOT/project-dry.log" 2>&1
grep -q 'Dry run only' "$TMP_ROOT/project-dry.log" || fail "project bridge dry-run message missing"
! grep -q 'RESEARCH_AGENT_SKILLS:START' "$project/AGENTS.md" || fail "project bridge dry-run wrote file"
./harness init "$project" --bridge -y >"$TMP_ROOT/project-apply.log" 2>&1
grep -q 'PROJECT HEADER' "$project/AGENTS.md" || fail "project bridge replaced existing content"
grep -q 'RESEARCH_AGENT_SKILLS:START' "$project/AGENTS.md" || fail "project bridge missing"
./harness init "$project" --bridge -y >"$TMP_ROOT/project-idempotent.log" 2>&1
[[ "$(grep -c 'RESEARCH_AGENT_SKILLS:START' "$project/AGENTS.md")" == "1" ]] || fail "project bridge duplicated"
./harness rollback --scope project "$project" -y >"$TMP_ROOT/project-rollback.log" 2>&1
grep -q '^PROJECT HEADER$' "$project/AGENTS.md" || fail "project rollback did not restore header"
! grep -q 'RESEARCH_AGENT_SKILLS:START' "$project/AGENTS.md" || fail "project rollback left bridge"

full="$TMP_ROOT/full-project"
mkdir -p "$full"
./harness init "$full" --full -y >"$TMP_ROOT/full.log" 2>&1
cmp -s templates/research/AGENTS.md "$full/AGENTS.md" || fail "full template install differs"
printf '%s\n' 'EXISTING' > "$full/AGENTS.md"
if ./harness init "$full" --full -y >"$TMP_ROOT/full-protect.log" 2>&1; then
  fail "full template replaced existing AGENTS.md without --replace"
fi
grep -q '^EXISTING$' "$full/AGENTS.md" || fail "full-template protection changed existing file"

global_home="$TMP_ROOT/global-home"
mkdir -p "$global_home"
printf '%s\n' 'GLOBAL HEADER' > "$global_home/AGENTS.md"
./harness global --codex-home "$global_home" >"$TMP_ROOT/global-dry.log" 2>&1
! grep -q 'RESEARCH_AGENT_SKILLS:START' "$global_home/AGENTS.md" || fail "global dry-run wrote file"
./harness global --codex-home "$global_home" -y >"$TMP_ROOT/global-apply.log" 2>&1
grep -q 'GLOBAL HEADER' "$global_home/AGENTS.md" || fail "global bridge replaced header"
grep -q 'RESEARCH_AGENT_SKILLS:START' "$global_home/AGENTS.md" || fail "global bridge missing"
./harness global --codex-home "$global_home" --remove -y >"$TMP_ROOT/global-remove.log" 2>&1
! grep -q 'RESEARCH_AGENT_SKILLS:START' "$global_home/AGENTS.md" || fail "global bridge removal failed"
./harness rollback --scope global --codex-home "$global_home" -y >"$TMP_ROOT/global-rollback.log" 2>&1
grep -q 'RESEARCH_AGENT_SKILLS:START' "$global_home/AGENTS.md" || fail "global rollback did not restore bridge"

path_case="$TMP_ROOT/path-independent"
mkdir -p "$path_case/plain" "$path_case/stubbed" "$path_case/bin"
printf '%s\n' 'HEADER' > "$path_case/plain/AGENTS.md"
printf '%s\n' 'HEADER' > "$path_case/stubbed/AGENTS.md"
legacy_name="$(printf 'o%s' 'mx')"
printf '%s\n' '#!/usr/bin/env sh' 'exit 97' > "$path_case/bin/$legacy_name"
chmod +x "$path_case/bin/$legacy_name"
PATH="/usr/bin:/bin" ./harness init "$path_case/plain" -y >"$TMP_ROOT/path-plain.log" 2>&1
PATH="$path_case/bin:/usr/bin:/bin" ./harness init "$path_case/stubbed" -y >"$TMP_ROOT/path-stub.log" 2>&1
cmp -s "$path_case/plain/AGENTS.md" "$path_case/stubbed/AGENTS.md" || fail "bridge depends on unrelated executable presence"
pass "prompt bridge/full-template dry-run, apply, idempotency, protection, backup, rollback, removal, and path independence"

doctor_codex="$TMP_ROOT/doctor-codex"
doctor_claude="$TMP_ROOT/doctor-claude"
./harness install --scope user --surface both --mode copy --codex-home "$doctor_codex" --claude-home "$doctor_claude" >"$TMP_ROOT/doctor-install.log" 2>&1
./harness doctor --strict --surface both --codex-home "$doctor_codex" --claude-home "$doctor_claude" >"$TMP_ROOT/doctor-pass.log" 2>&1 || fail "strict doctor rejected correct fixture (log $TMP_ROOT/doctor-pass.log)"
grep -q 'Doctor result: PASS' "$TMP_ROOT/doctor-pass.log" || fail "strict doctor PASS summary missing"

doctor_case() {
  local name="$1"
  local case_root="$TMP_ROOT/doctor-$name"
  cp -R "$doctor_codex" "$case_root-codex"
  cp -R "$doctor_claude" "$case_root-claude"
  echo "$case_root"
}

case_root="$(doctor_case wrong-model)"
python3 - "$case_root-codex/agents/coresearch-planner.toml" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
path.write_text(path.read_text().replace('model = "gpt-5.6-sol"', 'model = "wrong-model"', 1))
PY
if ./harness doctor --strict --surface both --codex-home "$case_root-codex" --claude-home "$case_root-claude" >"$TMP_ROOT/doctor-wrong-model.log" 2>&1; then fail "doctor accepted wrong model"; fi
grep -q 'CONFIG-MISMATCH' "$TMP_ROOT/doctor-wrong-model.log" || fail "wrong-model diagnostic missing"

case_root="$(doctor_case wrong-effort)"
python3 - "$case_root-codex/agents/coresearch-planner.toml" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
path.write_text(path.read_text().replace('model_reasoning_effort = "xhigh"', 'model_reasoning_effort = "low"', 1))
PY
if ./harness doctor --strict --surface both --codex-home "$case_root-codex" --claude-home "$case_root-claude" >"$TMP_ROOT/doctor-wrong-effort.log" 2>&1; then fail "doctor accepted wrong effort"; fi
grep -q 'CONFIG-MISMATCH' "$TMP_ROOT/doctor-wrong-effort.log" || fail "wrong-effort diagnostic missing"

case_root="$(doctor_case alias)"
python3 - "$case_root-claude/agents/coresearch-planner.md" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
path.write_text(path.read_text().replace('model: claude-opus-5', 'model: opus', 1))
PY
if ./harness doctor --strict --surface both --codex-home "$case_root-codex" --claude-home "$case_root-claude" >"$TMP_ROOT/doctor-alias.log" 2>&1; then fail "doctor accepted rolling alias"; fi
grep -q 'observed=opus' "$TMP_ROOT/doctor-alias.log" || fail "alias diagnostic missing observed value"

case_root="$(doctor_case missing)"
unlink "$case_root-codex/agents/coresearch-reader.toml"
if ./harness doctor --strict --surface both --codex-home "$case_root-codex" --claude-home "$case_root-claude" >"$TMP_ROOT/doctor-missing.log" 2>&1; then fail "doctor accepted missing role"; fi
grep -q 'coresearch-reader: missing' "$TMP_ROOT/doctor-missing.log" || fail "missing-role diagnostic absent"

case_root="$(doctor_case broken)"
unlink "$case_root-claude/agents/coresearch-reader.md"
ln -s "$case_root-claude/agents/does-not-exist.md" "$case_root-claude/agents/coresearch-reader.md"
if ./harness doctor --strict --surface both --codex-home "$case_root-codex" --claude-home "$case_root-claude" >"$TMP_ROOT/doctor-broken.log" 2>&1; then fail "doctor accepted broken role link"; fi
grep -q 'symlink:BROKEN' "$TMP_ROOT/doctor-broken.log" || fail "broken-link diagnostic absent"

if CLAUDE_CODE_SUBAGENT_MODEL=claude-sonnet-5 ./harness doctor --strict --surface both --codex-home "$doctor_codex" --claude-home "$doctor_claude" >"$TMP_ROOT/doctor-override.log" 2>&1; then fail "doctor accepted Claude environment override"; fi
grep -q 'CLAUDE_CODE_SUBAGENT_MODEL overrides Coresearch Claude role pins' "$TMP_ROOT/doctor-override.log" || fail "override diagnostic absent"

grep -q -- '--probe-models' <(./harness doctor --help) || fail "explicit model probe option missing"
if PATH="/usr/bin:/bin" ./harness doctor --strict --surface codex --probe-models --codex-home "$doctor_codex" --claude-home "$TMP_ROOT/probe-empty-claude" >"$TMP_ROOT/probe-codex-only.log" 2>&1; then
  fail "unobservable model probe was incorrectly reported as verified"
fi
grep -q 'routing provider=codex role=coresearch-reader .*status=static-only' "$TMP_ROOT/probe-codex-only.log" || fail "Codex static-only named-role probe record missing"
[[ "$(grep -c '^routing provider=codex role=' "$TMP_ROOT/probe-codex-only.log")" == "8" ]] || fail "Codex probe did not report all eight named roles"
if grep -q 'routing provider=claude' "$TMP_ROOT/probe-codex-only.log"; then
  fail "Codex-only probe contacted or reported the unselected Claude provider"
fi

probe_bin="$TMP_ROOT/probe-bin"
mkdir -p "$probe_bin"
cat >"$probe_bin/codex" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
for arg in "$@"; do
  [[ "$arg" != "--model" ]] || exit 90
done
role=""
for candidate in coresearch-planner coresearch-researcher coresearch-reader coresearch-implementer coresearch-experimenter coresearch-debugger coresearch-synthesizer coresearch-verifier; do
  [[ "$*" != *"$candidate"* ]] || role="$candidate"
done
[[ -n "$role" ]]
config="$CODEX_HOME/agents/$role.toml"
model="$(sed -n 's/^model = "\(.*\)"/\1/p' "$config")"
effort="$(sed -n 's/^model_reasoning_effort = "\(.*\)"/\1/p' "$config")"
printf '{"agent_type":"%s","model":"%s","model_reasoning_effort":"%s","text":"CORESEARCH_ROLE_PROBE %s"}\n' "$role" "$model" "$effort" "$role"
SH
cat >"$probe_bin/claude" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
role=""
while (($#)); do
  case "$1" in
    --agent) role="$2"; shift 2 ;;
    --model|--effort) exit 90 ;;
    *) shift ;;
  esac
done
[[ -n "$role" ]]
config="$CLAUDE_CONFIG_DIR/agents/$role.md"
model="$(sed -n 's/^model: //p' "$config")"
effort="$(sed -n 's/^effort: //p' "$config")"
printf '{"agent_type":"%s","model":"%s","effort":"%s","result":"CORESEARCH_ROLE_PROBE %s"}\n' "$role" "$model" "$effort" "$role"
SH
chmod +x "$probe_bin/codex" "$probe_bin/claude"
PATH="$probe_bin:/usr/bin:/bin" ./harness doctor --strict --surface both --probe-models --codex-home "$doctor_codex" --claude-home "$doctor_claude" >"$TMP_ROOT/probe-named-roles.log" 2>&1 || fail "named-role probe rejected exact fixture (log $TMP_ROOT/probe-named-roles.log)"
[[ "$(grep -c '^routing provider=codex role=.*status=verified$' "$TMP_ROOT/probe-named-roles.log")" == "8" ]] || fail "Codex named-role probes did not verify all roles"
[[ "$(grep -c '^routing provider=claude role=.*status=verified$' "$TMP_ROOT/probe-named-roles.log")" == "8" ]] || fail "Claude named-role probes did not verify all roles"
pass "strict doctor rejects config drift and environment overrides; named-role probes avoid invocation overrides and preserve static-only semantics"

pass "all validations completed"
